#!/bin/sh
#
# akvavit -- a rsnapshot wrapper
#
# Usage: akvavit routine [mount_point] 
#
# Copyright (c) 2015, Joel A. Nilsson <joel@alikzus.se>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#

routine="$1"
mount_point="$2"

abort() {
	exit 1
}

usage() {
	echo
	echo "Usage: ${0##*/} routine [mount_point]" >&2
	echo
	abort
}

pr_err() {
	echo "!!! ${@}"
}

pr() {
	echo "==> ${@}"
}

trap "abort" 1 2 3 13 15

if [ "$(id -u)" -ne 0 ]; then
    pr_err "Need root privileges to run"
    usage
fi

if [ -z "${routine}" ]; then
    usage
fi

if [ ! -z "${mount_point}" ]; then
    /sbin/mount ${mount_point}
fi

if [ "${routine}" == "hourly" ]; then
    /usr/local/bin/rsnapshot hourly
elif [ "${routine}" == "daily" ]; then
    /usr/local/bin/rsnapshot daily
elif [ "${routine}" == "weekly" ]; then
    /usr/local/bin/rsnapshot weekly
elif [ "${routine}" == "monthly" ]; then
    /usr/local/bin/rsnapshot monthly
else
    usage
fi

if [ ! -z ${mount_point} ]; then
    /sbin/umount ${mount_point}
fi

################################################################################
# Last updated: 2015-09-16 18:54:03 CEST

