#!/bin/sh
#
# check-host -- check if one or several hosts are alive and use pushover to send
#               a notification upon a negative response
#
# Usage: check-host [-f] filename/host
#
# Copyright (c) 2015, Joel A. Nilsson <joel@alikzus.se>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#

abort() {
	exit 1
}

usage() {
	echo
	echo "Usage: ${0##*/} [-f] filename/host" >&2
	echo
	echo "Options:"
    echo "  -f    read host(s) from the specified file"
	echo
	abort
}

pr_err() {
	echo "!!! ${@}"
}

pr() {
	echo "==> ${@}"
}

send_msg() {
    # Pushover format: title message
    /usr/local/bin/pushover ${_HOST} "$1"
}

check() {
    cache="${_TMPDIR}/$1"

    /sbin/ping -c 5 -q $1 > /dev/null

    if [ $? -gt 0 ]; then
        if [ -f ${cache} ]; then
            if [ `/usr/bin/find ${cache} -mmin +60` ]; then
                touch ${cache}
                send_msg "$1 is still NOT responding to pings"
            fi
        else
            touch ${cache}
            send_msg "$1 is NOT responding to pings"
        fi
    else
        if [ -f ${cache} ]; then
            rm ${cache}
            send_msg "$1 has started to respond to pings again"
        fi
    fi
}

trap "abort" 1 2 3 13 15

_HOST=`/bin/hostname -s`
_TMPDIR="/tmp/check-host"

while getopts 'f' arg; do
	case ${arg} in
	f)	plural=1 ;;
	*)	usage ;;
	esac
done

# TODO Check options and arguments further

if [ ! -d ${_TMPDIR} ]; then
    /bin/mkdir ${_TMPDIR}
fi

if [ "${plural}" -eq 1 ]; then
    hosts=`cat $2`
    
    for host in ${hosts}; do
        check ${host}
    done
else
    check $1
fi

################################################################################
# Last updated: 2015-10-11 10:43:24 CEST

