#!/bin/sh
#
# Copyright (c) 2015-2016, Joel A. Nilsson <joel@alikzus.se>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#

# TODO Source USER, PASS and HOSTS from file(s).

set -u

CACHE="/tmp/loopiadns"
URL="https://dns.loopia.se/XDynDNSServer/XDynDNS.php"

address=`/usr/local/bin/curl -s dns.loopia.se/checkip/checkip.php | sed 's/^.*: \([^<]*\).*$/\1/'`

if [ -f $CACHE ]; then
    last_address=`cat $CACHE`
else
    last_address=""
fi

if [ "$address" != "$last_address" ]; then
    echo -n $address > $CACHE

    for host in $HOSTS; do
        respons=`/usr/local/bin/curl -s -u $USER:$PASS "$URL?hostname=$host&myip=$address"`
        printf "%-24s %s\n" $host $respons
    done

    echo "\nDone!"
else
    echo "\nNothing done!"
fi

################################################################################
# Last Changed: 2016-04-17 14:37:29 CEST
