#!/bin/sh
#
# mount_sshfs
#
# Usage: mount_sshfs user volume
#
# Copyright (c) 2016, Joel A. Nilsson <joel@alikzus.se>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#

################################################################################
# PRAGMAS
################################################################################

set -u

################################################################################
# ARGUMENTS
################################################################################

if [ "$#" -eq 3 ]; then
    username="$1"
    volume="$2"
    user_options="$3"
elif [ "$#" -eq 2 ]; then
    username="$1"
    volume="$2"
    user_options=""
elif [ "$#" -eq 1 ]; then
    username="$1"
    volume="${username}"
    user_options=""
else
    usage
fi

################################################################################
# PARAMETERS
################################################################################

HOST="sftp"

local_path="/Volumes/${volume}"
remote_path="/home/${volume}"

################################################################################
# CONSTANTS
################################################################################

PROGRAM_NAME="mount_sshfs"

################################################################################
# FUNCTIONS
################################################################################

message() {
    /usr/bin/logger -t "${PROGRAM_NAME}" "${*}"
}

error() {
    /usr/bin/logger -t "${PROGRAM_NAME}" "${*}"
    abort
}

abort() {
    message "Aborted"
    if [ -d "${local_path}" ]; then
        /bin/rmdir "${local_path}"
    fi
    exit 1
}

usage() {
echo
echo "Usage: ${PROGRAM_NAME} username [volume] [sshfs_options]" >&2
echo
echo "  If volume is omitted it is assumed to be equal to the username"
echo "  volume is required if sshfs_options is provided"
echo "  sshfs_options is comma-separated, see sshfs(1)"
echo
exit 1
}

################################################################################
# MAIN
################################################################################

trap "abort" 1 2 3 13 15

message "username=${username}" "volume=${volume}"

if [ ! -d "${local_path}" ]; then
    message "Creating directory ${local_path}"
    /bin/mkdir "${local_path}" \
        || error "Could NOT create the directory ${local_path}"
else
    message "The directory ${local_path} already exists"
fi

DEFAULT_OPTIONS="volname=${volume}"

if [ -z "${user_options}" ]; then
    sshfs_options="${DEFAULT_OPTIONS}"
else
    sshfs_options="${DEFAULT_OPTIONS},${user_options}"
fi

if ! /sbin/mount | /usr/bin/grep -q "${local_path}"; then
    message "Mounting remote filesystem"
    if /sbin/ping -oc 60 "${HOST}"; then
        /usr/local/bin/sshfs "${username}@${HOST}:${remote_path}" \
            "${local_path}" -o "${sshfs_options}" 2>&1 \
            | /usr/bin/logger -t "${PROGRAM_NAME}"
    else
        error "No response from the host ${HOST}"
    fi
else
    message "The remote filesystem is already mounted"
fi

message "Done"
exit

################################################################################
# Last Changed: 2016-04-17 16:42:20 CEST
