#!/bin/sh
#
# mpd-www -- copy artwork from a music directory used by mpd to a www chroot
#
# Usage: mpd-www music_dir www_dir
#
# Copyright (c) 2015, Joel A. Nilsson <joel@alikzus.se>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#

MAX_THREADS="2" # preferably the number of real CPU cores

abort() {
	exit 1
}

pr_err() {
	echo "!!! ${@}"
}

pr() {
	echo "==> ${@}"
}

trap "abort" 1 2 3 13 15

MUSIC_DIR="$1"
WWW_DIR="$2"

targets=`find ${MUSIC_DIR}/ -name Folder.jpg`

for target in ${targets}; do
    album_path=`dirname ${target}`
    artist_path=`dirname ${album_path}`
    album=`basename ${album_path}`
    artist=`basename ${artist_path}`
    destination="${WWW_DIR}/${artist}/${album}"

    if [ ! -d ${destination} ]; then
        mkdir -p ${destination}
    fi

    if [ ! -f ${destination}/Folder.jpg ]; then
        cp ${target} ${destination}/Folder.jpg
        pr "${destination}"
    fi

#    while [ $(jobs | wc -l) -ge "${MAX_THREADS}" ]; do
#        sleep 0.1
#    done
done

################################################################################
# Last Changed: 2016-04-17 14:43:23 CEST
