#!/bin/sh
#
# Copyright (c) 2015-2016, Joel A. Nilsson <joel@alikzus.se>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#

# TODO Use option to switch between update and secure mode.

ocpath='/var/www/owncloud'
htuser='www'

#-------------------------------------------------------------------------------

find ${ocpath}/ -type f -print0 | xargs -0 chmod 0640
find ${ocpath}/ -type d -print0 | xargs -0 chmod 0750

#-------------------------------------------------------------------------------
# Update mode

#chown -R ${htuser}:${htuser} ${ocpath}/
#chown -R ${htuser}:${htuser} ${ocpath}-data/

#-------------------------------------------------------------------------------
# Secure mode

chown -R root:${htuser} ${ocpath}/
chown -R ${htuser}:${htuser} ${ocpath}/apps/
chown -R ${htuser}:${htuser} ${ocpath}/config/
chown -R ${htuser}:${htuser} ${ocpath}-data/
chown root:${htuser} ${ocpath}/.htaccess
chown root:${htuser} ${ocpath}-data/.htaccess

#-------------------------------------------------------------------------------

chmod 0644 ${ocpath}/.htaccess
chmod 0644 ${ocpath}-data/.htaccess

################################################################################
# Last Changed: 2016-04-17 14:41:33 CEST
