#!/bin/sh
#
# tvilling -- yet another Duplicity wrapper
#
# Usage: tvilling name command
#
# Copyright (c) 2015-2016, Joel A. Nilsson <joel@alikzus.se>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
################################################################################

set -u

#-------------------------------------------------------------------------------

ARCHIVE_DIR="/var/duplicity"
TEMPORARY_DIR="/tmp/duplicity" # tmpfs

#-------------------------------------------------------------------------------

abort() {
    # TODO Check if mounted
    /sbin/umount -f ${TEMPORARY_DIR} || echo "TODO"
    say "Aborted"
	exit 1
}

error() {
	echo "!!! ${*}"
    abort
}

say() {
	echo "==> ${*}"
}

usage() {
	echo "Usage: ${0##*/} name command" >&2
    echo
    echo "    name       backup name"
    echo "    command    make/purge/status"  
	echo
	exit 1
}

#-------------------------------------------------------------------------------

dump_database() {
    # TODO Variable
    cd /var/postgresql || error "Cannot find the directory"
    /usr/bin/doas -u _postgresql /usr/local/bin/pg_dumpall -U postgres \
        > /home/.postgresql/duplicity.sqldump \
        || error "Problem with the database dumping"
}

copy_www() {
    # TODO Variable
    /usr/local/bin/rsync -qa --delete /var/www/* /home/.www \
        || error "Problem with the WWW archiving"
}

#-------------------------------------------------------------------------------

make_backup() {
    say "Making a backup"

    #action="--dry-run -vI"
    action=""

    dump_database
    copy_www

    if ! [ -d "${TEMPORARY_DIR}" ]; then
        mkdir ${TEMPORARY_DIR}
    fi
    /sbin/mount -st tmpfs -o -s4G -o -uroot -o -gwheel -o -m0600 tmpfs ${TEMPORARY_DIR}

    GPG_options="--compress-algo=none -z 0 --cipher-algo=aes256 --digest-algo=sha512"
    exclude_list="${ARCHIVE_DIR}/${name}/exclude.lst"

    duplicity $action \
        --archive-dir ${ARCHIVE_DIR} \
        --encrypt-key "${GPG_KEY}" \
        --name "${name}" \
        --exclude-filelist "${exclude_list}" \
        --num-retries 3 \
        --asynchronous-upload \
        --volsize 1000 \
        --gpg-options "${GPG_options}" \
        --tempdir ${TEMPORARY_DIR} \
        "${SOURCE_DIR}" "${TARGET_URL}" \
        || error "Problem with Duplicity"

    /sbin/umount -f ${TEMPORARY_DIR}
}

purge_backup() {
    say "Purging the backup chain"

    #action="remove-all-but-n-full 1 --force"
    #action="remove-all-inc-of-but-n-full 1 --force"
}

check_backup() {
    say "Checking the backup archive"

    #action="status"
}

#-------------------------------------------------------------------------------

trap "abort" 1 2 3 13 15

if [ "$(id -u)" -ne 0 ]; then
	error "Need root privileges to run"
fi

if [ "$#" -eq 2 ]; then
    name="$1"       # backup name
    command="$2"
else
    usage
fi

if ! [ -d "${ARCHIVE_DIR}/${name}" ]; then
    error "Missing a configuration for ${name}"
fi

if [ -f "${ARCHIVE_DIR}/${name}/tvilling.conf" ]; then
    # shellcheck source=/dev/null
    . "${ARCHIVE_DIR}/${name}/tvilling.conf"
else
    error "Missing the configuration file for ${name}"
fi

if [ "${command}" = "make" ]; then
    make_backup
elif [ "${command}" = "purge" ]; then
    purge_backup
elif [ "${command}" = "check" ]; then
    check_backup
else
    usage
fi

say "Done"
exit 0

################################################################################
# Last Changed: 2016-08-10 16:38:03 CEST
